language: python

python:
   - 3.6

dist: bionic

branches:
  only:
    - master
    - development

before_install:
  - sudo apt-get install libgfortran3 gcc wget

install:
    - sudo apt-get update
    - pip install -r requirements.txt
    - pip install casatools==6.0.0.27 --index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple --no-cache-dir
    - pip install casatasks==6.0.0.27 --index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple --no-cache-dir
    - pip install casadata --index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple --no-cache-dir
    - pip install git+https://github.com/dsa110/dsa110-antpos.git
    - pip install git+https://github.com/dsa110/dsa110-pyutils.git@ds/dev
    - pip install git+https://github.com/dsa110/dsa110-calib.git
    - python setup.py develop --no-deps

before_script:
  - git config --global user.email "dana.simard@gmail.com"
  - git config --global user.name "Travis-CI"

script:
  - coverage run -m pytest

after_success:
  - coverage report
  - codecov

notifications:
  email: false

