name: Python Package using Conda

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        path: dsa110-meridian-fs
        fetch-depth: 0
    - name: Checkout antpos
      uses: actions/checkout@v3
      with:
        repository: dsa110/dsa110-antpos
        path: dsa110-antpos
        fetch-depth: 0
    - name: Checkout pyuvdata 
      uses: actions/checkout@v3
      with:
        repository: dsa110/pyuvdata
        path: pyuvdata
        fetch-depth: 0
    - name: Checkout dsa110-calib
      uses: actions/checkout@v3
      with:
        repository: dsa110/dsa110-calib
        path: dsa110-calib
        fetch-depth: 0
    - name: Checkout pyutils
      uses: actions/checkout@v3
      with:
        repository: dsa110/dsa110-pyutils
        path: dsa110-pyutils
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file $GITHUB_WORKSPACE/dsa110-meridian-fs/environment.yml --name base
    - name: Install dsa110 dependencies
      run: |
        cd $GITHUB_WORKSPACE/dsa110-pyutils ; git fetch --tags --force ; python setup.py install
        cd $GITHUB_WORKSPACE/dsa110-antpos ; git fetch --tags --force ; python setup.py install 
        cd $GITHUB_WORKSPACE/pyuvdata ; git fetch --tags --force ; pip install .
        cd $GITHUB_WORKSPACE/dsa110-calib ; git fetch --tags --force ; python setup.py install
    - name: Install
      run: |
        cd $GITHUB_WORKSPACE/dsa110-meridian-fs ; git fetch --tags --force ; python setup.py install
    - name: Test with pytest
      run: |
        conda install pytest
        pytest $GITHUB_WORKSPACE/dsa110-meridian-fs/tests
