name: Python Package using Conda

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        git clone https://github.com/dsa110/dsa110-antpos
        cd dsa110-antpos
        pip install -r requirements.txt
        pip install .
        cd ..
        git clone https://github.com/dsa110/dsa110-pyutils
        cd dsa110-pyutils
        pip install .
        cd ..
        git clone https://github.com/dsa110/pyuvdata
        cd pyuvdata
        pip install .
        cd ..
        python setup.py develop --no-deps
        git clone https://github.com/dsa110/dsa110-calib
        cd dsa110-calib
        pip install .
        cd ..
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
